function heat_map = fastheatmap(x, y, fixation_time, def, opts)
% FASTHEATMAP generates a 2D heat map from x, y and time input data.
%
%   HEAT_MAP = FASTHEATMAP(X, Y, T, DEF) creates heat map with defaults
%   options.
%   By default, HEAT_MAP is generated by smoothing the time spent on
%   each point of the image.
%
%   X and Y vector values must be between 0 and 1 and represent the
%   percentage of the respective image dimension, the origin point being at
%   top-left corner. T must be in milliseconds and should start at 0ms. DEF
%   is the screen pixels definition (the number of pixel in each dimension,
%   this is somethimes (wrongly) known as resolution), DEF is an array of
%   two integers first one being the number of lines and second the number
%   of columns.
%  
%   HEAT_MAP = FASTHEATMAP(X, Y, T, DEF, OPTS) creates heat map with custom
%   options.
%   If TIME_SMOOTH is false, the HEAT_MAP is generated by smoothing along
%   the two spacial dimensions and time dimension and flatten to a 2-D image
%   if FLATTEN is true.
%
%   You can apply custom options using the OPTS structure. The possible
%   fields in OPTS are:
%
%   Field Name : Description
%   -----------------------------------------------------------
%   KSSTD      : Kernel spatial standard deviation (default: 5)
%   KSSTDX     : Kernel spatial standard deviation in X direction (default: KSSTD)
%   KSSTDX     : Kernel spatial standard deviation in Y direction (default: KSSTD)
%   KTSTD      : Kernel time standard deviation (default: 2)
%   TIME_SMOOTH: See above, (default: true)
%   RESIZE     : If true, HEAT_MAP is resized to the provided definition (default: true)
%   NORMALIZE  : If true, HEAT_MAP is normalized against the maximum (default: true)
%   FLATTEN    : If true, HEAT_MAP is flatten to a 2D image (default: false)
%
% T. Perret (2019-03)
% G. Lio (2017)

if exist('opts', 'var')
    if isfield(opts, 'ksstd')
        ksstd = opts.ksstd;
    else
        ksstd = 5;
    end
    if isfield(opts, 'ksstdx')
        ksstdx = 100 * opts.ksstdx / def(1);
%         ksstdx = opts.ksstdx;
    else
        ksstdx = ksstd;
    end
    if isfield(opts, 'ksstdy')
        ksstdy = 100 * opts.ksstdy / def(1);
%         ksstdy = opts.ksstdy;
    else
        ksstdy = ksstd;
    end
    if isfield(opts, 'ktstd')
        ktstd = opts.ktstd;
    else
        ktstd = 2;
    end
    if isfield(opts, 'resize')
        resize = opts.resize;
    else
        resize = true;
    end
    if isfield(opts, 'normalize')
        normalize_heat_map = opts.normalize;
    else
        normalize_heat_map = true;
    end
    if isfield(opts, 'flatten')
        flatten = opts.flatten;
    else
        flatten = false;
    end
    if isfield(opts, 'time_smooth')
        time_smooth = opts.time_smooth;
    else
        time_smooth = false;
    end
else
    ksstd = 5;
    ksstdx = ksstd;
    ksstdy = ksstd;
    ktstd = 2;
    resize = true;
    normalize_heat_map = true;
    flatten = false;
    time_smooth = false;
end

width = def(2);
height = def(1);

if time_smooth
    x_ind = round(x * 99 * width/height) + 1;
    y_ind = round(y * 99) + 1;
    heat_map_lr = zeros(100, round(100 * width/height), length(fixation_time));
    for i = 1:length(fixation_time)
        heat_map_lr(y_ind(i), x_ind(i), i) = heat_map_lr(y_ind(i), x_ind(i), i) + fixation_time(i);
    end
    
    heat_map_lr = filter_3d_heat_map(heat_map_lr, ksstdx, ksstdy, ktstd);
    
    if flatten
        heat_map_lr = sum(heat_map_lr, 3);
    end
    
    if resize
        heat_map = zeros(def(1), def(2), size(heat_map_lr, 3));
        for i = 1:size(heat_map_lr, 3)
            heat_map(:, :, i) = imresize(heat_map_lr(:, :, i), [def(1), def(2)]);
        end
    else
        heat_map = heat_map_lr;
    end
else
    ksstdx = ksstdx * height / 100;
    ksstdy = ksstdy * height / 100;
    x_ind = round(x * (width - 1)) + 1;
    y_ind = round(y * (height - 1)) +1;
    heat_map = zeros(height, width);
    for i = 1:length(fixation_time)
        heat_map(y_ind(i), x_ind(i)) = heat_map(y_ind(i), x_ind(i)) + fixation_time(i);
    end
    heat_map = filter_2d_heat_map(heat_map, ksstdx, ksstdy);
end

if normalize_heat_map
    heat_map = (heat_map - min(heat_map, [], 'all')) ./ (max(heat_map, [], 'all') - min(heat_map, [], 'all'));
end
